name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
